### ISSUE TITLE
can't compile 

### ISSUE THREAD

**Issue by glebone** [danwdart/humblr#2]
can't compile with Glasgow Haskell Compiler, Version 7.6.3
src/Web/Tumblr.hs:82:22:
    `Request' is applied to too many type arguments
    In the type signature for`tumblrBaseRequest':
      tumblrBaseRequest :: Request m

**Comment by danwdart** [comment]
Looks like this is way out of date, might have to update for newer reqs...

**Comment by danwdart** [comment]
cabal file should probably restrict the version of req atm, will fork and have a look

**Comment by Taneb** [comment]
I'm sorry, I'm no longer interested in maintaining this library

**Comment by danwdart** [comment]
I'll take it then, as I've still got use for it, Seems like there's no stackage snapshots that are still up that even match the version requirements,,,

**Comment by danwdart** [comment]
Shall I fork and you point it there, or do you want to transfer ownership so that redirects happen automatically?

**Comment by Taneb** [comment]
I'll transfer ownership

**Comment by danwdart** [comment]
Alright cool

**Comment by danwdart** [comment]
Ta!

**Comment by danwdart** [comment]
Updated to fix this - now compiles with 8.8.
